#!/bin/bash
#
# git-hclone 
#
# I want to git clone a rep with web url
#
# https://github.com/raml-org/raml-examples
#
# but the address of the repo is actually
#
# git@github.com:raml-org/raml-examples.git

hclone_url() {
    web_url=$1
    hclone_base=$(echo $web_url |
                      sed "s/.*\/\///" |
                      sed "s/\//:/" |
                      sed -E "s/\/([^\/]+)\/.*/\/\1/")
    echo "git@${hclone_base}.git"
}

web_url=$1

git_url=$(hclone_url $web_url)

git clone $git_url
